VirtualPadの作成
WBC-Project/TGS2018PJT pull request #9
Opened 2018-08-29 09:39 UTC by AkiraSekine

2018-08-29 10:31 UTC, axluse requested changes

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +using Microsoft.Win32;
[MUST] すみませんこのL1-L2 なんですが、僕が追加しておいてなんですが、いらないので消してください。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +        private bool execute = false;
[IMO] L22-23って、いりますか？

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +
[MUST]
private Vector2 currentStickPosition;
private Vector2 baseStickPosition;

上の二つが必ず必要かと。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +        }
[MUST]baseのポジションは変わらないことが想定です。
basePositionはAwake時にキャッシュしておき、それを再利用するようにしたい。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +        }
[MUST] 自動で挿入してしまったのですが、ここも使っていないので、削除しましょう。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			    return;
[MUST]
コーディング規約通りに記述して欲しく、、、
今後もちょくちょく発生しているif文の{}なしはエラーの原因です。

去年のCEDECの「ゼルダエラー」でも話題になっていましたが、インデントの明示化は後々の開発速度を上昇させる上に、テストケースが単純になるので、機械的に変更や察知ができるようになるんですよね。
その文脈から、{}を省略した書き方はC#やUnityの公式でもフォーラム上がってますが省略を良しとしていません。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			stickImage.rectTransform.position = (Vector2)baseTransform.position + eventData.position - eventData.pressPosition;
[MUST] stickTransformでいいんじゃないでしょうか？

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			stickImage.rectTransform.position = (Vector2)baseTransform.position + eventData.position - eventData.pressPosition;
[MUST] baseTransform.positionも変わらない値であると思うので前項で指摘を入れた通り、再利用できるようにしましょう。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			if (Vector3.Distance(stickTransform.position, baseTransform.position) >= baseRadius)
[MUST] Distanceおよびmagnitudeは平方根ですよね。。。使いたくないです。
平方根を求めて、比較するより2項の値の２乗で比較をした方がパフォーマンスが良い気がします。

と言うことはmagnitudeを使わず、sqrMagnitudeを使うべきとなるはず。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +        private bool execute = false;
[MUST] executeは「実行する」という意味で、booleanな命名ではありませんね。
isExecutedとかが望ましいのでは？

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +		private bool isShow = true;
HideもあるのでisEnabledVirtualPadとかの方が明確な気がする。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +            execute = false;
[MUST]
this.Hide();
がほしい

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +            if(stickTransform.rect.Contains((Vector3)eventData.pressPosition - stickTransform.position))
[MUST] {}は省略してはいけません

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +        }
[MUST] this.Show();がほしい。

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +            float distance = Vector2.Distance(stickPos, basePos);
[MUST] Distanceは使わない

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			return difference.normalized * (distance / baseRadius);
[MUST] normalizeも同様で使わない

2018-08-29 10:31 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			isShow = false;
[IMO] いらない気がします。

2018-08-29 17:42 UTC, reito13 approved these changes

2018-08-30 10:51 UTC, axluse requested changes
もうちょっと修正をお願いします

2018-08-30 10:51 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +                Debug.LogError("failed Initialized()");
[MUST] Debug.Log関数はビルドしても動くんですよ。。これ
なので、あらかじめL135のようにエスケープしないといけません。
でも、エスケープめんどくさいのでNotifyError()を使ってるんですよね。

2018-08-30 10:51 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +			    return;
[nits] 超細かいんですがここtabっすよね

2018-08-30 10:59 UTC, axluse requested changes

2018-08-30 10:59 UTC, axluse commented on Assets/TGS/Scripts/Presenter/UI/VirtualPad.cs
> +            Vector2 axises;
[MUST]変数は必ずNull回避しておきましょう。

2018-08-30 11:30 UTC, axluse commented
good

2018-08-30 11:30 UTC, axluse approved these changes

2018-08-30 11:31 UTC, merged